// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: account.sql

package db

import (
	"context"
    "database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password
) VALUES (
    $1, $2
) RETURNING id, email, password
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// 新規ユーザ情報登録関数
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

// フォームのメールアドレスからDB登録済みの既存ユーザ情報を検索し、取得する関数
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
    var user User

    row := q.db.QueryRowContext(ctx, `SELECT id, email, password FROM users WHERE email = $1`, email)
    err := row.Scan(&user.ID, &user.Email, &user.Password)
    if err != nil {
        if err == sql.ErrNoRows {
            return nil, nil
        }
        return nil, err
    }
    return &user, nil
}
