// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: create_message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    sender_id,
    receiver_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id
`

type CreateMessageParams struct {
	SenderID   int32  `json:"sender_id"`
	ReceiverID int32  `json:"receiver_id"`
	Content    string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.exec(ctx, q.createMessageStmt, createMessage, arg.SenderID, arg.ReceiverID, arg.Content)
	return err
}
