// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBookmarkStmt, err = db.PrepareContext(ctx, createBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookmark: %w", err)
	}
	if q.createFollowStmt, err = db.PrepareContext(ctx, createFollow); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFollow: %w", err)
	}
	if q.createLikeStmt, err = db.PrepareContext(ctx, createLike); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLike: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createRetweetStmt, err = db.PrepareContext(ctx, createRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRetweet: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteBookmarkStmt, err = db.PrepareContext(ctx, deleteBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmark: %w", err)
	}
	if q.deleteFollowStmt, err = db.PrepareContext(ctx, deleteFollow); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFollow: %w", err)
	}
	if q.deleteLikeStmt, err = db.PrepareContext(ctx, deleteLike); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLike: %w", err)
	}
	if q.deleteRetweetStmt, err = db.PrepareContext(ctx, deleteRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRetweet: %w", err)
	}
	if q.deleteTweetStmt, err = db.PrepareContext(ctx, deleteTweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTweet: %w", err)
	}
	if q.getBookmarkStmt, err = db.PrepareContext(ctx, getBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmark: %w", err)
	}
	if q.getBookmarksStmt, err = db.PrepareContext(ctx, getBookmarks); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmarks: %w", err)
	}
	if q.getLikeStmt, err = db.PrepareContext(ctx, getLike); err != nil {
		return nil, fmt.Errorf("error preparing query GetLike: %w", err)
	}
	if q.getRetweetStmt, err = db.PrepareContext(ctx, getRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query GetRetweet: %w", err)
	}
	if q.getTweetByIDStmt, err = db.PrepareContext(ctx, getTweetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetByID: %w", err)
	}
	if q.getTweetDetailStmt, err = db.PrepareContext(ctx, getTweetDetail); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetDetail: %w", err)
	}
	if q.getTweetDetailReplyStmt, err = db.PrepareContext(ctx, getTweetDetailReply); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetDetailReply: %w", err)
	}
	if q.getTweetsStmt, err = db.PrepareContext(ctx, getTweets); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweets: %w", err)
	}
	if q.getUserByActivationTokenStmt, err = db.PrepareContext(ctx, getUserByActivationToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByActivationToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserInfoStmt, err = db.PrepareContext(ctx, getUserInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInfo: %w", err)
	}
	if q.insertReplyStmt, err = db.PrepareContext(ctx, insertReply); err != nil {
		return nil, fmt.Errorf("error preparing query InsertReply: %w", err)
	}
	if q.insertTweetStmt, err = db.PrepareContext(ctx, insertTweet); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTweet: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBookmarkStmt != nil {
		if cerr := q.createBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookmarkStmt: %w", cerr)
		}
	}
	if q.createFollowStmt != nil {
		if cerr := q.createFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFollowStmt: %w", cerr)
		}
	}
	if q.createLikeStmt != nil {
		if cerr := q.createLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLikeStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createRetweetStmt != nil {
		if cerr := q.createRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRetweetStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteBookmarkStmt != nil {
		if cerr := q.deleteBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarkStmt: %w", cerr)
		}
	}
	if q.deleteFollowStmt != nil {
		if cerr := q.deleteFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFollowStmt: %w", cerr)
		}
	}
	if q.deleteLikeStmt != nil {
		if cerr := q.deleteLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikeStmt: %w", cerr)
		}
	}
	if q.deleteRetweetStmt != nil {
		if cerr := q.deleteRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRetweetStmt: %w", cerr)
		}
	}
	if q.deleteTweetStmt != nil {
		if cerr := q.deleteTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTweetStmt: %w", cerr)
		}
	}
	if q.getBookmarkStmt != nil {
		if cerr := q.getBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarkStmt: %w", cerr)
		}
	}
	if q.getBookmarksStmt != nil {
		if cerr := q.getBookmarksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarksStmt: %w", cerr)
		}
	}
	if q.getLikeStmt != nil {
		if cerr := q.getLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLikeStmt: %w", cerr)
		}
	}
	if q.getRetweetStmt != nil {
		if cerr := q.getRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRetweetStmt: %w", cerr)
		}
	}
	if q.getTweetByIDStmt != nil {
		if cerr := q.getTweetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetByIDStmt: %w", cerr)
		}
	}
	if q.getTweetDetailStmt != nil {
		if cerr := q.getTweetDetailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetDetailStmt: %w", cerr)
		}
	}
	if q.getTweetDetailReplyStmt != nil {
		if cerr := q.getTweetDetailReplyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetDetailReplyStmt: %w", cerr)
		}
	}
	if q.getTweetsStmt != nil {
		if cerr := q.getTweetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsStmt: %w", cerr)
		}
	}
	if q.getUserByActivationTokenStmt != nil {
		if cerr := q.getUserByActivationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByActivationTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserInfoStmt != nil {
		if cerr := q.getUserInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInfoStmt: %w", cerr)
		}
	}
	if q.insertReplyStmt != nil {
		if cerr := q.insertReplyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertReplyStmt: %w", cerr)
		}
	}
	if q.insertTweetStmt != nil {
		if cerr := q.insertTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTweetStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	createBookmarkStmt           *sql.Stmt
	createFollowStmt             *sql.Stmt
	createLikeStmt               *sql.Stmt
	createMessageStmt            *sql.Stmt
	createRetweetStmt            *sql.Stmt
	createUserStmt               *sql.Stmt
	deleteBookmarkStmt           *sql.Stmt
	deleteFollowStmt             *sql.Stmt
	deleteLikeStmt               *sql.Stmt
	deleteRetweetStmt            *sql.Stmt
	deleteTweetStmt              *sql.Stmt
	getBookmarkStmt              *sql.Stmt
	getBookmarksStmt             *sql.Stmt
	getLikeStmt                  *sql.Stmt
	getRetweetStmt               *sql.Stmt
	getTweetByIDStmt             *sql.Stmt
	getTweetDetailStmt           *sql.Stmt
	getTweetDetailReplyStmt      *sql.Stmt
	getTweetsStmt                *sql.Stmt
	getUserByActivationTokenStmt *sql.Stmt
	getUserByEmailStmt           *sql.Stmt
	getUserInfoStmt              *sql.Stmt
	insertReplyStmt              *sql.Stmt
	insertTweetStmt              *sql.Stmt
	updateUserStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		createBookmarkStmt:           q.createBookmarkStmt,
		createFollowStmt:             q.createFollowStmt,
		createLikeStmt:               q.createLikeStmt,
		createMessageStmt:            q.createMessageStmt,
		createRetweetStmt:            q.createRetweetStmt,
		createUserStmt:               q.createUserStmt,
		deleteBookmarkStmt:           q.deleteBookmarkStmt,
		deleteFollowStmt:             q.deleteFollowStmt,
		deleteLikeStmt:               q.deleteLikeStmt,
		deleteRetweetStmt:            q.deleteRetweetStmt,
		deleteTweetStmt:              q.deleteTweetStmt,
		getBookmarkStmt:              q.getBookmarkStmt,
		getBookmarksStmt:             q.getBookmarksStmt,
		getLikeStmt:                  q.getLikeStmt,
		getRetweetStmt:               q.getRetweetStmt,
		getTweetByIDStmt:             q.getTweetByIDStmt,
		getTweetDetailStmt:           q.getTweetDetailStmt,
		getTweetDetailReplyStmt:      q.getTweetDetailReplyStmt,
		getTweetsStmt:                q.getTweetsStmt,
		getUserByActivationTokenStmt: q.getUserByActivationTokenStmt,
		getUserByEmailStmt:           q.getUserByEmailStmt,
		getUserInfoStmt:              q.getUserInfoStmt,
		insertReplyStmt:              q.insertReplyStmt,
		insertTweetStmt:              q.insertTweetStmt,
		updateUserStmt:               q.updateUserStmt,
	}
}
