// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBookmarkStmt, err = db.PrepareContext(ctx, createBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookmark: %w", err)
	}
	if q.createFollowStmt, err = db.PrepareContext(ctx, createFollow); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFollow: %w", err)
	}
	if q.createLikeStmt, err = db.PrepareContext(ctx, createLike); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLike: %w", err)
	}
	if q.createRetweetStmt, err = db.PrepareContext(ctx, createRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRetweet: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteBookmarkStmt, err = db.PrepareContext(ctx, deleteBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmark: %w", err)
	}
	if q.deleteBookmarksByTweetUserIDStmt, err = db.PrepareContext(ctx, deleteBookmarksByTweetUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmarksByTweetUserID: %w", err)
	}
	if q.deleteBookmarksByUserIDStmt, err = db.PrepareContext(ctx, deleteBookmarksByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmarksByUserID: %w", err)
	}
	if q.deleteFollowStmt, err = db.PrepareContext(ctx, deleteFollow); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFollow: %w", err)
	}
	if q.deleteFollowsByUserIDStmt, err = db.PrepareContext(ctx, deleteFollowsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFollowsByUserID: %w", err)
	}
	if q.deleteLikeStmt, err = db.PrepareContext(ctx, deleteLike); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLike: %w", err)
	}
	if q.deleteLikesByUserIDStmt, err = db.PrepareContext(ctx, deleteLikesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLikesByUserID: %w", err)
	}
	if q.deleteMessagesByUserIDStmt, err = db.PrepareContext(ctx, deleteMessagesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessagesByUserID: %w", err)
	}
	if q.deleteNotificationsByUserIDStmt, err = db.PrepareContext(ctx, deleteNotificationsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNotificationsByUserID: %w", err)
	}
	if q.deleteRepliesByUserIDStmt, err = db.PrepareContext(ctx, deleteRepliesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRepliesByUserID: %w", err)
	}
	if q.deleteReplyStmt, err = db.PrepareContext(ctx, deleteReply); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteReply: %w", err)
	}
	if q.deleteRetweetStmt, err = db.PrepareContext(ctx, deleteRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRetweet: %w", err)
	}
	if q.deleteRetweetOfTweetStmt, err = db.PrepareContext(ctx, deleteRetweetOfTweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRetweetOfTweet: %w", err)
	}
	if q.deleteRetweetsByUserIDStmt, err = db.PrepareContext(ctx, deleteRetweetsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRetweetsByUserID: %w", err)
	}
	if q.deleteTweetStmt, err = db.PrepareContext(ctx, deleteTweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTweet: %w", err)
	}
	if q.deleteTweetsByUserIDStmt, err = db.PrepareContext(ctx, deleteTweetsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTweetsByUserID: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getBookmarkStmt, err = db.PrepareContext(ctx, getBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmark: %w", err)
	}
	if q.getBookmarksStmt, err = db.PrepareContext(ctx, getBookmarks); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmarks: %w", err)
	}
	if q.getFollowByUserIdStmt, err = db.PrepareContext(ctx, getFollowByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetFollowByUserId: %w", err)
	}
	if q.getFollowsStmt, err = db.PrepareContext(ctx, getFollows); err != nil {
		return nil, fmt.Errorf("error preparing query GetFollows: %w", err)
	}
	if q.getLikeStmt, err = db.PrepareContext(ctx, getLike); err != nil {
		return nil, fmt.Errorf("error preparing query GetLike: %w", err)
	}
	if q.getMessagesStmt, err = db.PrepareContext(ctx, getMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessages: %w", err)
	}
	if q.getNotificationsStmt, err = db.PrepareContext(ctx, getNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotifications: %w", err)
	}
	if q.getRetweetStmt, err = db.PrepareContext(ctx, getRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query GetRetweet: %w", err)
	}
	if q.getTweetByIDStmt, err = db.PrepareContext(ctx, getTweetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetByID: %w", err)
	}
	if q.getTweetDetailStmt, err = db.PrepareContext(ctx, getTweetDetail); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetDetail: %w", err)
	}
	if q.getTweetDetailReplyStmt, err = db.PrepareContext(ctx, getTweetDetailReply); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetDetailReply: %w", err)
	}
	if q.getTweetsStmt, err = db.PrepareContext(ctx, getTweets); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweets: %w", err)
	}
	if q.getTweetsByUserStmt, err = db.PrepareContext(ctx, getTweetsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByUser: %w", err)
	}
	if q.getUserByActivationTokenStmt, err = db.PrepareContext(ctx, getUserByActivationToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByActivationToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserInfoStmt, err = db.PrepareContext(ctx, getUserInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserInfo: %w", err)
	}
	if q.insertMessageStmt, err = db.PrepareContext(ctx, insertMessage); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMessage: %w", err)
	}
	if q.insertNotificationStmt, err = db.PrepareContext(ctx, insertNotification); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNotification: %w", err)
	}
	if q.insertReplyStmt, err = db.PrepareContext(ctx, insertReply); err != nil {
		return nil, fmt.Errorf("error preparing query InsertReply: %w", err)
	}
	if q.insertTweetStmt, err = db.PrepareContext(ctx, insertTweet); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTweet: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBookmarkStmt != nil {
		if cerr := q.createBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookmarkStmt: %w", cerr)
		}
	}
	if q.createFollowStmt != nil {
		if cerr := q.createFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFollowStmt: %w", cerr)
		}
	}
	if q.createLikeStmt != nil {
		if cerr := q.createLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLikeStmt: %w", cerr)
		}
	}
	if q.createRetweetStmt != nil {
		if cerr := q.createRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRetweetStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteBookmarkStmt != nil {
		if cerr := q.deleteBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarkStmt: %w", cerr)
		}
	}
	if q.deleteBookmarksByTweetUserIDStmt != nil {
		if cerr := q.deleteBookmarksByTweetUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarksByTweetUserIDStmt: %w", cerr)
		}
	}
	if q.deleteBookmarksByUserIDStmt != nil {
		if cerr := q.deleteBookmarksByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarksByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteFollowStmt != nil {
		if cerr := q.deleteFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFollowStmt: %w", cerr)
		}
	}
	if q.deleteFollowsByUserIDStmt != nil {
		if cerr := q.deleteFollowsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFollowsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteLikeStmt != nil {
		if cerr := q.deleteLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikeStmt: %w", cerr)
		}
	}
	if q.deleteLikesByUserIDStmt != nil {
		if cerr := q.deleteLikesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteMessagesByUserIDStmt != nil {
		if cerr := q.deleteMessagesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessagesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteNotificationsByUserIDStmt != nil {
		if cerr := q.deleteNotificationsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNotificationsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteRepliesByUserIDStmt != nil {
		if cerr := q.deleteRepliesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRepliesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteReplyStmt != nil {
		if cerr := q.deleteReplyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteReplyStmt: %w", cerr)
		}
	}
	if q.deleteRetweetStmt != nil {
		if cerr := q.deleteRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRetweetStmt: %w", cerr)
		}
	}
	if q.deleteRetweetOfTweetStmt != nil {
		if cerr := q.deleteRetweetOfTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRetweetOfTweetStmt: %w", cerr)
		}
	}
	if q.deleteRetweetsByUserIDStmt != nil {
		if cerr := q.deleteRetweetsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRetweetsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteTweetStmt != nil {
		if cerr := q.deleteTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTweetStmt: %w", cerr)
		}
	}
	if q.deleteTweetsByUserIDStmt != nil {
		if cerr := q.deleteTweetsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTweetsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getBookmarkStmt != nil {
		if cerr := q.getBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarkStmt: %w", cerr)
		}
	}
	if q.getBookmarksStmt != nil {
		if cerr := q.getBookmarksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarksStmt: %w", cerr)
		}
	}
	if q.getFollowByUserIdStmt != nil {
		if cerr := q.getFollowByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFollowByUserIdStmt: %w", cerr)
		}
	}
	if q.getFollowsStmt != nil {
		if cerr := q.getFollowsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFollowsStmt: %w", cerr)
		}
	}
	if q.getLikeStmt != nil {
		if cerr := q.getLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLikeStmt: %w", cerr)
		}
	}
	if q.getMessagesStmt != nil {
		if cerr := q.getMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessagesStmt: %w", cerr)
		}
	}
	if q.getNotificationsStmt != nil {
		if cerr := q.getNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotificationsStmt: %w", cerr)
		}
	}
	if q.getRetweetStmt != nil {
		if cerr := q.getRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRetweetStmt: %w", cerr)
		}
	}
	if q.getTweetByIDStmt != nil {
		if cerr := q.getTweetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetByIDStmt: %w", cerr)
		}
	}
	if q.getTweetDetailStmt != nil {
		if cerr := q.getTweetDetailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetDetailStmt: %w", cerr)
		}
	}
	if q.getTweetDetailReplyStmt != nil {
		if cerr := q.getTweetDetailReplyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetDetailReplyStmt: %w", cerr)
		}
	}
	if q.getTweetsStmt != nil {
		if cerr := q.getTweetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsStmt: %w", cerr)
		}
	}
	if q.getTweetsByUserStmt != nil {
		if cerr := q.getTweetsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByUserStmt: %w", cerr)
		}
	}
	if q.getUserByActivationTokenStmt != nil {
		if cerr := q.getUserByActivationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByActivationTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserInfoStmt != nil {
		if cerr := q.getUserInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserInfoStmt: %w", cerr)
		}
	}
	if q.insertMessageStmt != nil {
		if cerr := q.insertMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMessageStmt: %w", cerr)
		}
	}
	if q.insertNotificationStmt != nil {
		if cerr := q.insertNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNotificationStmt: %w", cerr)
		}
	}
	if q.insertReplyStmt != nil {
		if cerr := q.insertReplyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertReplyStmt: %w", cerr)
		}
	}
	if q.insertTweetStmt != nil {
		if cerr := q.insertTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTweetStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createBookmarkStmt               *sql.Stmt
	createFollowStmt                 *sql.Stmt
	createLikeStmt                   *sql.Stmt
	createRetweetStmt                *sql.Stmt
	createUserStmt                   *sql.Stmt
	deleteBookmarkStmt               *sql.Stmt
	deleteBookmarksByTweetUserIDStmt *sql.Stmt
	deleteBookmarksByUserIDStmt      *sql.Stmt
	deleteFollowStmt                 *sql.Stmt
	deleteFollowsByUserIDStmt        *sql.Stmt
	deleteLikeStmt                   *sql.Stmt
	deleteLikesByUserIDStmt          *sql.Stmt
	deleteMessagesByUserIDStmt       *sql.Stmt
	deleteNotificationsByUserIDStmt  *sql.Stmt
	deleteRepliesByUserIDStmt        *sql.Stmt
	deleteReplyStmt                  *sql.Stmt
	deleteRetweetStmt                *sql.Stmt
	deleteRetweetOfTweetStmt         *sql.Stmt
	deleteRetweetsByUserIDStmt       *sql.Stmt
	deleteTweetStmt                  *sql.Stmt
	deleteTweetsByUserIDStmt         *sql.Stmt
	deleteUserStmt                   *sql.Stmt
	getBookmarkStmt                  *sql.Stmt
	getBookmarksStmt                 *sql.Stmt
	getFollowByUserIdStmt            *sql.Stmt
	getFollowsStmt                   *sql.Stmt
	getLikeStmt                      *sql.Stmt
	getMessagesStmt                  *sql.Stmt
	getNotificationsStmt             *sql.Stmt
	getRetweetStmt                   *sql.Stmt
	getTweetByIDStmt                 *sql.Stmt
	getTweetDetailStmt               *sql.Stmt
	getTweetDetailReplyStmt          *sql.Stmt
	getTweetsStmt                    *sql.Stmt
	getTweetsByUserStmt              *sql.Stmt
	getUserByActivationTokenStmt     *sql.Stmt
	getUserByEmailStmt               *sql.Stmt
	getUserInfoStmt                  *sql.Stmt
	insertMessageStmt                *sql.Stmt
	insertNotificationStmt           *sql.Stmt
	insertReplyStmt                  *sql.Stmt
	insertTweetStmt                  *sql.Stmt
	updateUserStmt                   *sql.Stmt
	updateUserProfileStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createBookmarkStmt:               q.createBookmarkStmt,
		createFollowStmt:                 q.createFollowStmt,
		createLikeStmt:                   q.createLikeStmt,
		createRetweetStmt:                q.createRetweetStmt,
		createUserStmt:                   q.createUserStmt,
		deleteBookmarkStmt:               q.deleteBookmarkStmt,
		deleteBookmarksByTweetUserIDStmt: q.deleteBookmarksByTweetUserIDStmt,
		deleteBookmarksByUserIDStmt:      q.deleteBookmarksByUserIDStmt,
		deleteFollowStmt:                 q.deleteFollowStmt,
		deleteFollowsByUserIDStmt:        q.deleteFollowsByUserIDStmt,
		deleteLikeStmt:                   q.deleteLikeStmt,
		deleteLikesByUserIDStmt:          q.deleteLikesByUserIDStmt,
		deleteMessagesByUserIDStmt:       q.deleteMessagesByUserIDStmt,
		deleteNotificationsByUserIDStmt:  q.deleteNotificationsByUserIDStmt,
		deleteRepliesByUserIDStmt:        q.deleteRepliesByUserIDStmt,
		deleteReplyStmt:                  q.deleteReplyStmt,
		deleteRetweetStmt:                q.deleteRetweetStmt,
		deleteRetweetOfTweetStmt:         q.deleteRetweetOfTweetStmt,
		deleteRetweetsByUserIDStmt:       q.deleteRetweetsByUserIDStmt,
		deleteTweetStmt:                  q.deleteTweetStmt,
		deleteTweetsByUserIDStmt:         q.deleteTweetsByUserIDStmt,
		deleteUserStmt:                   q.deleteUserStmt,
		getBookmarkStmt:                  q.getBookmarkStmt,
		getBookmarksStmt:                 q.getBookmarksStmt,
		getFollowByUserIdStmt:            q.getFollowByUserIdStmt,
		getFollowsStmt:                   q.getFollowsStmt,
		getLikeStmt:                      q.getLikeStmt,
		getMessagesStmt:                  q.getMessagesStmt,
		getNotificationsStmt:             q.getNotificationsStmt,
		getRetweetStmt:                   q.getRetweetStmt,
		getTweetByIDStmt:                 q.getTweetByIDStmt,
		getTweetDetailStmt:               q.getTweetDetailStmt,
		getTweetDetailReplyStmt:          q.getTweetDetailReplyStmt,
		getTweetsStmt:                    q.getTweetsStmt,
		getTweetsByUserStmt:              q.getTweetsByUserStmt,
		getUserByActivationTokenStmt:     q.getUserByActivationTokenStmt,
		getUserByEmailStmt:               q.getUserByEmailStmt,
		getUserInfoStmt:                  q.getUserInfoStmt,
		insertMessageStmt:                q.insertMessageStmt,
		insertNotificationStmt:           q.insertNotificationStmt,
		insertReplyStmt:                  q.insertReplyStmt,
		insertTweetStmt:                  q.insertTweetStmt,
		updateUserStmt:                   q.updateUserStmt,
		updateUserProfileStmt:            q.updateUserProfileStmt,
	}
}
