// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_retweet.sql

package db

import (
	"context"
)

const deleteRetweet = `-- name: DeleteRetweet :exec
DELETE FROM
    retweets
WHERE
    original_tweet_id = $1
    AND user_id = $2
`

type DeleteRetweetParams struct {
	OriginalTweetID int64 `json:"original_tweet_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) DeleteRetweet(ctx context.Context, arg DeleteRetweetParams) error {
	_, err := q.exec(ctx, q.deleteRetweetStmt, deleteRetweet, arg.OriginalTweetID, arg.UserID)
	return err
}

const deleteRetweetOfTweet = `-- name: DeleteRetweetOfTweet :exec
DELETE FROM
    tweets
WHERE
    id = $1
`

func (q *Queries) DeleteRetweetOfTweet(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteRetweetOfTweetStmt, deleteRetweetOfTweet, id)
	return err
}
