// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_like.sql

package db

import (
	"context"
)

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM
    likes
WHERE
    tweet_id = $1
    AND
    user_id = $2
`

type DeleteLikeParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.exec(ctx, q.deleteLikeStmt, deleteLike, arg.TweetID, arg.UserID)
	return err
}
