// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_bookmark.sql

package db

import (
	"context"
)

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM
    bookmarks
WHERE
    tweet_id = $1
    AND
    user_id = $2
`

type DeleteBookmarkParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.exec(ctx, q.deleteBookmarkStmt, deleteBookmark, arg.TweetID, arg.UserID)
	return err
}
