// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_user.sql

package db

import (
	"context"
)

const deleteBookmarksByTweetUserID = `-- name: DeleteBookmarksByTweetUserID :exec
DELETE FROM bookmarks WHERE tweet_id IN (SELECT id FROM tweets WHERE tweets.user_id = $1)
`

func (q *Queries) DeleteBookmarksByTweetUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteBookmarksByTweetUserIDStmt, deleteBookmarksByTweetUserID, userID)
	return err
}

const deleteBookmarksByUserID = `-- name: DeleteBookmarksByUserID :exec
DELETE FROM bookmarks WHERE user_id = $1
`

func (q *Queries) DeleteBookmarksByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteBookmarksByUserIDStmt, deleteBookmarksByUserID, userID)
	return err
}

const deleteFollowsByUserID = `-- name: DeleteFollowsByUserID :exec
DELETE FROM follows WHERE follower_id = $1 OR followee_id = $1
`

func (q *Queries) DeleteFollowsByUserID(ctx context.Context, followerID int64) error {
	_, err := q.exec(ctx, q.deleteFollowsByUserIDStmt, deleteFollowsByUserID, followerID)
	return err
}

const deleteLikesByUserID = `-- name: DeleteLikesByUserID :exec
DELETE FROM likes WHERE user_id = $1
`

func (q *Queries) DeleteLikesByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteLikesByUserIDStmt, deleteLikesByUserID, userID)
	return err
}

const deleteMessagesByUserID = `-- name: DeleteMessagesByUserID :exec
DELETE FROM messages WHERE sender_id = $1 OR receiver_id = $1
`

func (q *Queries) DeleteMessagesByUserID(ctx context.Context, senderID int64) error {
	_, err := q.exec(ctx, q.deleteMessagesByUserIDStmt, deleteMessagesByUserID, senderID)
	return err
}

const deleteNotificationsByUserID = `-- name: DeleteNotificationsByUserID :exec
DELETE FROM notifications WHERE user_id = $1
`

func (q *Queries) DeleteNotificationsByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteNotificationsByUserIDStmt, deleteNotificationsByUserID, userID)
	return err
}

const deleteRepliesByUserID = `-- name: DeleteRepliesByUserID :exec
DELETE FROM replies WHERE user_id = $1
`

func (q *Queries) DeleteRepliesByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteRepliesByUserIDStmt, deleteRepliesByUserID, userID)
	return err
}

const deleteRetweetsByUserID = `-- name: DeleteRetweetsByUserID :exec
DELETE FROM retweets WHERE user_id = $1
`

func (q *Queries) DeleteRetweetsByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteRetweetsByUserIDStmt, deleteRetweetsByUserID, userID)
	return err
}

const deleteTweetsByUserID = `-- name: DeleteTweetsByUserID :exec
DELETE FROM tweets WHERE user_id = $1
`

func (q *Queries) DeleteTweetsByUserID(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteTweetsByUserIDStmt, deleteTweetsByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}
