// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_follow.sql

package db

import (
	"context"
)

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM
    follows
WHERE
    follower_id = $1
    AND followee_id = $2
`

type DeleteFollowParams struct {
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.exec(ctx, q.deleteFollowStmt, deleteFollow, arg.FollowerID, arg.FolloweeID)
	return err
}
