// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_tweet.sql

package db

import (
	"context"
)

const deleteTweet = `-- name: DeleteTweet :exec
DELETE FROM
    tweets
WHERE
    id = $1
    AND
    user_id = $2
`

type DeleteTweetParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTweet(ctx context.Context, arg DeleteTweetParams) error {
	_, err := q.exec(ctx, q.deleteTweetStmt, deleteTweet, arg.ID, arg.UserID)
	return err
}
