// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_reply.sql

package db

import (
	"context"
)

const deleteReply = `-- name: DeleteReply :exec
DELETE FROM
    replies
WHERE
    id = $1
`

func (q *Queries) DeleteReply(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteReplyStmt, deleteReply, id)
	return err
}
