// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweet_replies.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetDetailReply = `-- name: GetTweetDetailReply :many
SELECT
    users.id AS user_id,
    users.display_name AS user_name,
    users.profile_image AS profile_image,
    replies.id AS reply_id,
    replies.tweet_id AS tweet_id,
    replies.content AS tweet_content,
    replies.image_path AS image_path,
    replies.created_at AS tweet_date,
    (SELECT COUNT(*) FROM likes WHERE likes.tweet_id = tweets.id) AS likes_count,
    (SELECT COUNT(*) FROM retweets WHERE retweets.tweet_id = tweets.id) AS retweets_count
FROM
    replies
JOIN
    users ON replies.user_id = users.id
JOIN
    tweets ON replies.tweet_id = tweets.id
WHERE
    replies.tweet_id = $1
ORDER BY
    replies.created_at DESC
`

type GetTweetDetailReplyRow struct {
	UserID        int64          `json:"user_id"`
	UserName      string         `json:"user_name"`
	ProfileImage  sql.NullString `json:"profile_image"`
	ReplyID       int64          `json:"reply_id"`
	TweetID       int64          `json:"tweet_id"`
	TweetContent  string         `json:"tweet_content"`
	ImagePath     sql.NullString `json:"image_path"`
	TweetDate     time.Time      `json:"tweet_date"`
	LikesCount    int64          `json:"likes_count"`
	RetweetsCount int64          `json:"retweets_count"`
}

func (q *Queries) GetTweetDetailReply(ctx context.Context, tweetID int64) ([]GetTweetDetailReplyRow, error) {
	rows, err := q.query(ctx, q.getTweetDetailReplyStmt, getTweetDetailReply, tweetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTweetDetailReplyRow
	for rows.Next() {
		var i GetTweetDetailReplyRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.ProfileImage,
			&i.ReplyID,
			&i.TweetID,
			&i.TweetContent,
			&i.ImagePath,
			&i.TweetDate,
			&i.LikesCount,
			&i.RetweetsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
