// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_bookmark.sql

package db

import (
	"context"
)

const getBookmark = `-- name: GetBookmark :one
SELECT
    id,
    tweet_id,
    user_id,
    created_at
FROM
    bookmarks
WHERE
    tweet_id = $1
    AND
    user_id = $2
`

type GetBookmarkParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetBookmark(ctx context.Context, arg GetBookmarkParams) (Bookmark, error) {
	row := q.queryRow(ctx, q.getBookmarkStmt, getBookmark, arg.TweetID, arg.UserID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.TweetID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
