// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_like.sql

package db

import (
	"context"
)

const getLike = `-- name: GetLike :one
SELECT
    id,
    tweet_id,
    user_id,
    created_at
FROM
    likes
WHERE
    tweet_id = $1
    AND
    user_id = $2
`

type GetLikeParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (Like, error) {
	row := q.queryRow(ctx, q.getLikeStmt, getLike, arg.TweetID, arg.UserID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.TweetID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
