// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweet_by_id.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetByID = `-- name: GetTweetByID :one
SELECT
    tweets.id,
    tweets.user_id,
    tweets.content,
    tweets.image_path,
    tweets.created_at,
    users.display_name
FROM
    tweets
JOIN
    users ON tweets.user_id = users.id
WHERE
    tweets.id = $1
`

type GetTweetByIDRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Content     string         `json:"content"`
	ImagePath   sql.NullString `json:"image_path"`
	CreatedAt   time.Time      `json:"created_at"`
	DisplayName string         `json:"display_name"`
}

func (q *Queries) GetTweetByID(ctx context.Context, id int64) (GetTweetByIDRow, error) {
	row := q.queryRow(ctx, q.getTweetByIDStmt, getTweetByID, id)
	var i GetTweetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ImagePath,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}
