// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getNotifications = `-- name: GetNotifications :many
SELECT
    n.notification_id,
    n.action_type,
    n.created_at AS notification_created_at,
    n.read,
    u.display_name AS action_user_display_name,
    u.profile_image AS action_user_profile_image,
    t.content AS related_tweet_content,
    t.image_path AS related_tweet_image_path,
    r.content AS related_reply_content
FROM
    notifications n
LEFT JOIN follows f ON n.action_type = 'follow' AND n.reference_id = f.followee_id
LEFT JOIN likes l ON n.action_type = 'like' AND n.reference_id = l.tweet_id AND n.user_id != l.user_id
LEFT JOIN replies r ON n.action_type = 'comment' AND n.reference_id = r.tweet_id AND n.user_id != r.user_id
LEFT JOIN tweets t ON t.id = l.tweet_id OR t.id = r.tweet_id
LEFT JOIN users u ON f.follower_id = u.id OR l.user_id = u.id OR r.user_id = u.id
WHERE
    n.user_id = $1
ORDER BY
    n.created_at DESC
`

type GetNotificationsRow struct {
	NotificationID         int64          `json:"notification_id"`
	ActionType             string         `json:"action_type"`
	NotificationCreatedAt  time.Time      `json:"notification_created_at"`
	Read                   bool           `json:"read"`
	ActionUserDisplayName  sql.NullString `json:"action_user_display_name"`
	ActionUserProfileImage sql.NullString `json:"action_user_profile_image"`
	RelatedTweetContent    sql.NullString `json:"related_tweet_content"`
	RelatedTweetImagePath  sql.NullString `json:"related_tweet_image_path"`
	RelatedReplyContent    sql.NullString `json:"related_reply_content"`
}

func (q *Queries) GetNotifications(ctx context.Context, userID int64) ([]GetNotificationsRow, error) {
	rows, err := q.query(ctx, q.getNotificationsStmt, getNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsRow
	for rows.Next() {
		var i GetNotificationsRow
		if err := rows.Scan(
			&i.NotificationID,
			&i.ActionType,
			&i.NotificationCreatedAt,
			&i.Read,
			&i.ActionUserDisplayName,
			&i.ActionUserProfileImage,
			&i.RelatedTweetContent,
			&i.RelatedTweetImagePath,
			&i.RelatedReplyContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
