// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweet_detail.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetDetail = `-- name: GetTweetDetail :one
SELECT
    users.id,
    users.display_name,
    users.profile_image AS user_image,
    users.avatar_image AS avatar_image,
    tweets.id AS tweet_id,
    tweets.content AS tweet_content,
    tweets.image_path AS image_path,
    tweets.created_at AS tweet_date
FROM
    tweets
JOIN
    users ON tweets.user_id = users.id
WHERE
    tweets.id = $1
`

type GetTweetDetailRow struct {
	ID           int64          `json:"id"`
	DisplayName  string         `json:"display_name"`
	UserImage    sql.NullString `json:"user_image"`
	AvatarImage  sql.NullString `json:"avatar_image"`
	TweetID      int64          `json:"tweet_id"`
	TweetContent string         `json:"tweet_content"`
	ImagePath    sql.NullString `json:"image_path"`
	TweetDate    time.Time      `json:"tweet_date"`
}

func (q *Queries) GetTweetDetail(ctx context.Context, id int64) (GetTweetDetailRow, error) {
	row := q.queryRow(ctx, q.getTweetDetailStmt, getTweetDetail, id)
	var i GetTweetDetailRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.UserImage,
		&i.AvatarImage,
		&i.TweetID,
		&i.TweetContent,
		&i.ImagePath,
		&i.TweetDate,
	)
	return i, err
}
