// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_user_info.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT
    id,
    email,
    password,
    phone_number,
    display_name,
    dio,
    location,
    website,
    birth_date,
    profile_image,
    header_image,
    created_at,
    is_active
FROM
    users
WHERE
    id = $1
`

type GetUserInfoRow struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	DisplayName  string         `json:"display_name"`
	Dio          sql.NullString `json:"dio"`
	Location     sql.NullString `json:"location"`
	Website      sql.NullString `json:"website"`
	BirthDate    sql.NullTime   `json:"birth_date"`
	ProfileImage sql.NullString `json:"profile_image"`
	HeaderImage  sql.NullString `json:"header_image"`
	CreatedAt    time.Time      `json:"created_at"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) GetUserInfo(ctx context.Context, id int64) (GetUserInfoRow, error) {
	row := q.queryRow(ctx, q.getUserInfoStmt, getUserInfo, id)
	var i GetUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.Dio,
		&i.Location,
		&i.Website,
		&i.BirthDate,
		&i.ProfileImage,
		&i.HeaderImage,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}
