// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweet_detail_reply.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetDetailReply = `-- name: GetTweetDetailReply :many
SELECT
    users.id,
    users.display_name,
    users.profile_image AS user_image,
    users.avatar_image AS avatar_image,
    tweets.id AS tweet_id,
    tweets.content AS tweet_content,
    tweets.image_path AS image_path,
    tweets.created_at AS tweet_date
FROM
    tweets
JOIN
    users ON tweets.user_id = users.id
WHERE
    tweets.reply_to = $1
ORDER BY
    tweets.created_at DESC
`

type GetTweetDetailReplyRow struct {
	ID           int64          `json:"id"`
	DisplayName  string         `json:"display_name"`
	UserImage    sql.NullString `json:"user_image"`
	AvatarImage  sql.NullString `json:"avatar_image"`
	TweetID      int64          `json:"tweet_id"`
	TweetContent string         `json:"tweet_content"`
	ImagePath    sql.NullString `json:"image_path"`
	TweetDate    time.Time      `json:"tweet_date"`
}

func (q *Queries) GetTweetDetailReply(ctx context.Context, replyTo sql.NullInt64) ([]GetTweetDetailReplyRow, error) {
	rows, err := q.query(ctx, q.getTweetDetailReplyStmt, getTweetDetailReply, replyTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTweetDetailReplyRow
	for rows.Next() {
		var i GetTweetDetailReplyRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.UserImage,
			&i.AvatarImage,
			&i.TweetID,
			&i.TweetContent,
			&i.ImagePath,
			&i.TweetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
