// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweet_replies.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetDetailReply = `-- name: GetTweetDetailReply :many
SELECT
    users.id,
    users.display_name,
    users.profile_image AS user_image,
    users.avatar_image AS avatar_image,
    replies.id AS reply_id,
    replies.tweet_id AS tweet_id,
    replies.content AS reply_content,
    replies.image_path AS image_path,
    replies.created_at AS reply_date
FROM
    replies
JOIN
    users ON replies.user_id = users.id
WHERE
    replies.tweet_id = $1
ORDER BY
    replies.created_at DESC
`

type GetTweetDetailReplyRow struct {
	ID           int64          `json:"id"`
	DisplayName  string         `json:"display_name"`
	UserImage    sql.NullString `json:"user_image"`
	AvatarImage  sql.NullString `json:"avatar_image"`
	ReplyID      int64          `json:"reply_id"`
	TweetID      int64          `json:"tweet_id"`
	ReplyContent string         `json:"reply_content"`
	ImagePath    sql.NullString `json:"image_path"`
	ReplyDate    time.Time      `json:"reply_date"`
}

func (q *Queries) GetTweetDetailReply(ctx context.Context, tweetID int64) ([]GetTweetDetailReplyRow, error) {
	rows, err := q.query(ctx, q.getTweetDetailReplyStmt, getTweetDetailReply, tweetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTweetDetailReplyRow
	for rows.Next() {
		var i GetTweetDetailReplyRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.UserImage,
			&i.AvatarImage,
			&i.ReplyID,
			&i.TweetID,
			&i.ReplyContent,
			&i.ImagePath,
			&i.ReplyDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
