// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_follows.sql

package db

import (
	"context"
	"database/sql"
)

const getFollows = `-- name: GetFollows :many
SELECT
    follows.follower_id,
    follows.followee_id,
    follows.created_at,
    users.display_name,
    COALESCE(users.profile_image, '') AS profile_image
FROM
    follows
INNER JOIN
    users ON follows.followee_id = users.id
WHERE
    follower_id = $1
ORDER BY
    follows.created_at DESC
`

type GetFollowsRow struct {
	FollowerID   int64        `json:"follower_id"`
	FolloweeID   int64        `json:"followee_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	DisplayName  string       `json:"display_name"`
	ProfileImage string       `json:"profile_image"`
}

func (q *Queries) GetFollows(ctx context.Context, followerID int64) ([]GetFollowsRow, error) {
	rows, err := q.query(ctx, q.getFollowsStmt, getFollows, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowsRow
	for rows.Next() {
		var i GetFollowsRow
		if err := rows.Scan(
			&i.FollowerID,
			&i.FolloweeID,
			&i.CreatedAt,
			&i.DisplayName,
			&i.ProfileImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
