// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_follow_by_userId.sql

package db

import (
	"context"
)

const getFollowByUserId = `-- name: GetFollowByUserId :one
SELECT
    COUNT(*)
FROM
    follows
WHERE
    follower_id = $1
    AND
    followee_id = $2
`

type GetFollowByUserIdParams struct {
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

func (q *Queries) GetFollowByUserId(ctx context.Context, arg GetFollowByUserIdParams) (int64, error) {
	row := q.queryRow(ctx, q.getFollowByUserIdStmt, getFollowByUserId, arg.FollowerID, arg.FolloweeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
