// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_user_by_activation_token.sql

package db

import (
	"context"
	"database/sql"
)

const getUserByActivationToken = `-- name: GetUserByActivationToken :one
SELECT
    id
FROM
    users
WHERE
    activation_token = $1
`

func (q *Queries) GetUserByActivationToken(ctx context.Context, activationToken sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.getUserByActivationTokenStmt, getUserByActivationToken, activationToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}
