// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_user_info.sql

package db

import (
	"context"
	"database/sql"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT
    id,
    email,
    password,
    phone_number,
    display_name,
    self_introduction,
    location,
    website,
    birth_date,
    profile_image,
    avatar_image,
    is_active
FROM
    users
WHERE
    email = $1
`

type GetUserInfoRow struct {
	ID               int64          `json:"id"`
	Email            string         `json:"email"`
	Password         string         `json:"password"`
	PhoneNumber      sql.NullString `json:"phone_number"`
	DisplayName      string         `json:"display_name"`
	SelfIntroduction sql.NullString `json:"self_introduction"`
	Location         sql.NullString `json:"location"`
	Website          sql.NullString `json:"website"`
	BirthDate        sql.NullTime   `json:"birth_date"`
	ProfileImage     sql.NullString `json:"profile_image"`
	AvatarImage      sql.NullString `json:"avatar_image"`
	IsActive         bool           `json:"is_active"`
}

func (q *Queries) GetUserInfo(ctx context.Context, email string) (GetUserInfoRow, error) {
	row := q.queryRow(ctx, q.getUserInfoStmt, getUserInfo, email)
	var i GetUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.SelfIntroduction,
		&i.Location,
		&i.Website,
		&i.BirthDate,
		&i.ProfileImage,
		&i.AvatarImage,
		&i.IsActive,
	)
	return i, err
}
