// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_bookmarks_by_userId.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getBookmarks = `-- name: GetBookmarks :many
SELECT
    users.id AS user_id,
    users.display_name AS user_name,
    users.profile_image AS user_image,
    tweets.id AS tweet_id,
    tweets.content AS tweet_content,
    tweets.image_path AS image_path,
    tweets.created_at AS tweet_date,
    tweets.is_retweet AS is_retweet,
    COALESCE(retweeters.display_name, '') AS retweeter_name,
    COUNT(DISTINCT replies.id) AS replies_count,
    COUNT(DISTINCT likes.id) AS likes_count,
    COUNT(DISTINCT retweets.id) AS retweets_count,
    EXISTS(SELECT 1 FROM bookmarks WHERE tweet_id = tweets.id AND user_id = bookmarks.user_id) AS is_bookmarked,
    CASE WHEN follows.follower_id IS NOT NULL THEN true ELSE false END AS is_following
FROM
    tweets
JOIN
    bookmarks ON tweets.id = bookmarks.tweet_id
JOIN
    users ON tweets.user_id = users.id
LEFT JOIN
    replies ON tweets.id = replies.tweet_id
LEFT JOIN
    retweets ON tweets.id = retweets.tweet_id
LEFT JOIN
    users AS retweeters ON retweets.user_id = retweeters.id AND tweets.id = retweets.tweet_id
LEFT JOIN
    likes ON tweets.id = likes.tweet_id
LEFT JOIN
    follows ON users.id = follows.followee_id AND follows.follower_id = bookmarks.user_id
WHERE
    bookmarks.user_id = $1
GROUP BY
    tweets.id, users.id, retweeters.id, bookmarks.user_id, follows.follower_id, bookmarks.created_at
ORDER BY
    bookmarks.created_at DESC
`

type GetBookmarksRow struct {
	UserID        int64          `json:"user_id"`
	UserName      string         `json:"user_name"`
	UserImage     sql.NullString `json:"user_image"`
	TweetID       int64          `json:"tweet_id"`
	TweetContent  string         `json:"tweet_content"`
	ImagePath     sql.NullString `json:"image_path"`
	TweetDate     time.Time      `json:"tweet_date"`
	IsRetweet     bool           `json:"is_retweet"`
	RetweeterName string         `json:"retweeter_name"`
	RepliesCount  int64          `json:"replies_count"`
	LikesCount    int64          `json:"likes_count"`
	RetweetsCount int64          `json:"retweets_count"`
	IsBookmarked  bool           `json:"is_bookmarked"`
	IsFollowing   bool           `json:"is_following"`
}

func (q *Queries) GetBookmarks(ctx context.Context, userID int64) ([]GetBookmarksRow, error) {
	rows, err := q.query(ctx, q.getBookmarksStmt, getBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksRow
	for rows.Next() {
		var i GetBookmarksRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.UserImage,
			&i.TweetID,
			&i.TweetContent,
			&i.ImagePath,
			&i.TweetDate,
			&i.IsRetweet,
			&i.RetweeterName,
			&i.RepliesCount,
			&i.LikesCount,
			&i.RetweetsCount,
			&i.IsBookmarked,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
