// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_tweets_by_user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTweetsByUser = `-- name: GetTweetsByUser :many
SELECT
    users.id AS user_id,
    users.display_name AS user_name,
    users.profile_image AS profile_image,
    tweets.id AS tweet_id,
    tweets.content AS tweet_content,
    tweets.image_path AS image_path,
    tweets.created_at AS tweet_date,
    tweets.is_retweet AS is_retweet,
    (SELECT COUNT(*) FROM follows WHERE follows.followee_id = users.id) AS followers_count,
    (SELECT COUNT(*) FROM follows WHERE follows.follower_id = users.id) AS following_count
FROM
    tweets
JOIN
    users ON tweets.user_id = users.id
WHERE
    tweets.user_id = $1
ORDER BY
    tweets.created_at DESC
`

type GetTweetsByUserRow struct {
	UserID         int64          `json:"user_id"`
	UserName       string         `json:"user_name"`
	ProfileImage   sql.NullString `json:"profile_image"`
	TweetID        int64          `json:"tweet_id"`
	TweetContent   string         `json:"tweet_content"`
	ImagePath      sql.NullString `json:"image_path"`
	TweetDate      time.Time      `json:"tweet_date"`
	IsRetweet      bool           `json:"is_retweet"`
	FollowersCount int64          `json:"followers_count"`
	FollowingCount int64          `json:"following_count"`
}

func (q *Queries) GetTweetsByUser(ctx context.Context, userID int64) ([]GetTweetsByUserRow, error) {
	rows, err := q.query(ctx, q.getTweetsByUserStmt, getTweetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTweetsByUserRow
	for rows.Next() {
		var i GetTweetsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.ProfileImage,
			&i.TweetID,
			&i.TweetContent,
			&i.ImagePath,
			&i.TweetDate,
			&i.IsRetweet,
			&i.FollowersCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
