// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: get_retweet.sql

package db

import (
	"context"
)

const getRetweet = `-- name: GetRetweet :one
SELECT
    id,
    tweet_id,
    user_id,
    original_tweet_id,
    created_at
FROM
    retweets
WHERE
    original_tweet_id = $1
    AND
    user_id = $2
`

type GetRetweetParams struct {
	OriginalTweetID int64 `json:"original_tweet_id"`
	UserID          int64 `json:"user_id"`
}

func (q *Queries) GetRetweet(ctx context.Context, arg GetRetweetParams) (Retweet, error) {
	row := q.queryRow(ctx, q.getRetweetStmt, getRetweet, arg.OriginalTweetID, arg.UserID)
	var i Retweet
	err := row.Scan(
		&i.ID,
		&i.TweetID,
		&i.UserID,
		&i.OriginalTweetID,
		&i.CreatedAt,
	)
	return i, err
}
