// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_retweet.sql

package db

import (
	"context"
)

const createRetweet = `-- name: CreateRetweet :exec
INSERT INTO retweets (
    tweet_id,
    user_id
) VALUES (
    $1, $2
)
`

type CreateRetweetParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CreateRetweet(ctx context.Context, arg CreateRetweetParams) error {
	_, err := q.exec(ctx, q.createRetweetStmt, createRetweet, arg.TweetID, arg.UserID)
	return err
}
