// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_bookmark.sql

package db

import (
	"context"
)

const createBookmark = `-- name: CreateBookmark :exec
INSERT INTO bookmarks (
    tweet_id,
    user_id
) VALUES (
    $1, $2
)
`

type CreateBookmarkParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error {
	_, err := q.exec(ctx, q.createBookmarkStmt, createBookmark, arg.TweetID, arg.UserID)
	return err
}
