// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_notification.sql

package db

import (
	"context"
)

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    user_id,
    action_type,
    reference_id
) VALUES (
    $1, $2, $3
) RETURNING notification_id, user_id, action_type, reference_id, read, created_at
`

type InsertNotificationParams struct {
	UserID      int64  `json:"user_id"`
	ActionType  string `json:"action_type"`
	ReferenceID int64  `json:"reference_id"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.queryRow(ctx, q.insertNotificationStmt, insertNotification, arg.UserID, arg.ActionType, arg.ReferenceID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.ActionType,
		&i.ReferenceID,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
