// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_comment.sql

package db

import (
	"context"
	"database/sql"
)

const insertReply = `-- name: InsertReply :one
INSERT INTO tweets (
    user_id,
    content,
    image_path,
    reply_to
) VALUES (
    $1, $2, $3, $4
) RETURNING user_id, content, image_path
`

type InsertReplyParams struct {
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
	ReplyTo   sql.NullInt64  `json:"reply_to"`
}

type InsertReplyRow struct {
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
}

func (q *Queries) InsertReply(ctx context.Context, arg InsertReplyParams) (InsertReplyRow, error) {
	row := q.queryRow(ctx, q.insertReplyStmt, insertReply,
		arg.UserID,
		arg.Content,
		arg.ImagePath,
		arg.ReplyTo,
	)
	var i InsertReplyRow
	err := row.Scan(&i.UserID, &i.Content, &i.ImagePath)
	return i, err
}
