// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_message.sql

package db

import (
	"context"
	"database/sql"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    sender_id,
    receiver_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING sender_id, receiver_id, content, created_at
`

type InsertMessageParams struct {
	SenderID   int64  `json:"sender_id"`
	ReceiverID int64  `json:"receiver_id"`
	Content    string `json:"content"`
}

type InsertMessageRow struct {
	SenderID   int64        `json:"sender_id"`
	ReceiverID int64        `json:"receiver_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.queryRow(ctx, q.insertMessageStmt, insertMessage, arg.SenderID, arg.ReceiverID, arg.Content)
	var i InsertMessageRow
	err := row.Scan(
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
