// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_reply.sql

package db

import (
	"context"
	"database/sql"
)

const insertReply = `-- name: InsertReply :one
INSERT INTO replies (
    tweet_id,
    user_id,
    content,
    image_path
) VALUES (
    $1, $2, $3, $4
) RETURNING tweet_id, user_id, content, image_path
`

type InsertReplyParams struct {
	TweetID   int64          `json:"tweet_id"`
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
}

type InsertReplyRow struct {
	TweetID   int64          `json:"tweet_id"`
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
}

func (q *Queries) InsertReply(ctx context.Context, arg InsertReplyParams) (InsertReplyRow, error) {
	row := q.queryRow(ctx, q.insertReplyStmt, insertReply,
		arg.TweetID,
		arg.UserID,
		arg.Content,
		arg.ImagePath,
	)
	var i InsertReplyRow
	err := row.Scan(
		&i.TweetID,
		&i.UserID,
		&i.Content,
		&i.ImagePath,
	)
	return i, err
}
