// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_tweet.sql

package db

import (
	"context"
	"database/sql"
)

const insertTweet = `-- name: InsertTweet :one
INSERT INTO tweets (
    user_id,
    content,
    image_path
) VALUES (
    $1, $2, $3
) RETURNING user_id, content, image_path
`

type InsertTweetParams struct {
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
}

type InsertTweetRow struct {
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
}

func (q *Queries) InsertTweet(ctx context.Context, arg InsertTweetParams) (InsertTweetRow, error) {
	row := q.queryRow(ctx, q.insertTweetStmt, insertTweet, arg.UserID, arg.Content, arg.ImagePath)
	var i InsertTweetRow
	err := row.Scan(&i.UserID, &i.Content, &i.ImagePath)
	return i, err
}
