// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_follow.sql

package db

import (
	"context"
)

const createFollow = `-- name: CreateFollow :exec
INSERT INTO follows (
    follower_id,
    followee_id
) VALUES (
    $1, $2
)
`

type CreateFollowParams struct {
	FollowerID int64 `json:"follower_id"`
	FolloweeID int64 `json:"followee_id"`
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.exec(ctx, q.createFollowStmt, createFollow, arg.FollowerID, arg.FolloweeID)
	return err
}
