// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_like.sql

package db

import (
	"context"
)

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (
    tweet_id,
    user_id
) VALUES (
    $1, $2
)
`

type CreateLikeParams struct {
	TweetID int64 `json:"tweet_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.exec(ctx, q.createLikeStmt, createLike, arg.TweetID, arg.UserID)
	return err
}
