// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Tweet struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Content      string         `json:"content"`
	ImagePath    sql.NullString `json:"image_path"`
	ReplyTo      sql.NullInt64  `json:"reply_to"`
	QuoteTweetID sql.NullInt64  `json:"quote_tweet_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Email            string         `json:"email"`
	Password         string         `json:"password"`
	PhoneNumber      sql.NullString `json:"phone_number"`
	DisplayName      string         `json:"display_name"`
	SelfIntroduction sql.NullString `json:"self_introduction"`
	Location         sql.NullString `json:"location"`
	Website          sql.NullString `json:"website"`
	BirthDate        sql.NullTime   `json:"birth_date"`
	ProfileImage     sql.NullString `json:"profile_image"`
	AvatarImage      sql.NullString `json:"avatar_image"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ActivationToken  sql.NullString `json:"activation_token"`
	IsActive         bool           `json:"is_active"`
}
