// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Bookmark struct {
	ID        int64     `json:"id"`
	TweetID   int64     `json:"tweet_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Follow struct {
	FollowerID int64        `json:"follower_id"`
	FolloweeID int64        `json:"followee_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Like struct {
	ID        int64     `json:"id"`
	TweetID   int64     `json:"tweet_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID         int64        `json:"id"`
	SenderID   int64        `json:"sender_id"`
	ReceiverID int64        `json:"receiver_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Reply struct {
	ID           int64          `json:"id"`
	TweetID      int64          `json:"tweet_id"`
	UserID       int64          `json:"user_id"`
	Content      string         `json:"content"`
	ImagePath    sql.NullString `json:"image_path"`
	QuoteTweetID sql.NullInt64  `json:"quote_tweet_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Retweet struct {
	ID        int64     `json:"id"`
	TweetID   int64     `json:"tweet_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Tweet struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Content   string         `json:"content"`
	ImagePath sql.NullString `json:"image_path"`
	IsRetweet bool           `json:"is_retweet"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type User struct {
	ID              int64          `json:"id"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	DisplayName     string         `json:"display_name"`
	Dio             sql.NullString `json:"dio"`
	Location        sql.NullString `json:"location"`
	Website         sql.NullString `json:"website"`
	BirthDate       sql.NullTime   `json:"birth_date"`
	ProfileImage    sql.NullString `json:"profile_image"`
	HeaderImage     sql.NullString `json:"header_image"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ActivationToken sql.NullString `json:"activation_token"`
	IsActive        bool           `json:"is_active"`
}
