// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: update_user_profile.sql

package db

import (
	"context"
	"database/sql"
)

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE
    users
SET
    display_name = $2
    , bio = $3
    , location = $4
    , website = $5
    , birth_date = $6
    , header_image = $7
    , profile_image = $8
WHERE
    id = $1
RETURNING
    id,
    display_name,
    bio,
    location,
    website,
    birth_date,
    header_image,
    profile_image
`

type UpdateUserProfileParams struct {
	ID           int64          `json:"id"`
	DisplayName  string         `json:"display_name"`
	Bio          sql.NullString `json:"bio"`
	Location     sql.NullString `json:"location"`
	Website      sql.NullString `json:"website"`
	BirthDate    sql.NullTime   `json:"birth_date"`
	HeaderImage  sql.NullString `json:"header_image"`
	ProfileImage sql.NullString `json:"profile_image"`
}

type UpdateUserProfileRow struct {
	ID           int64          `json:"id"`
	DisplayName  string         `json:"display_name"`
	Bio          sql.NullString `json:"bio"`
	Location     sql.NullString `json:"location"`
	Website      sql.NullString `json:"website"`
	BirthDate    sql.NullTime   `json:"birth_date"`
	HeaderImage  sql.NullString `json:"header_image"`
	ProfileImage sql.NullString `json:"profile_image"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.Website,
		arg.BirthDate,
		arg.HeaderImage,
		arg.ProfileImage,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bio,
		&i.Location,
		&i.Website,
		&i.BirthDate,
		&i.HeaderImage,
		&i.ProfileImage,
	)
	return i, err
}
