// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: update_user.sql

package db

import (
	"context"
	"database/sql"
)

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    activation_token = $2
    , is_active = $3
WHERE
    id = $1 RETURNING id,
    activation_token,
    is_active
`

type UpdateUserParams struct {
	ID              int64          `json:"id"`
	ActivationToken sql.NullString `json:"activation_token"`
	IsActive        bool           `json:"is_active"`
}

type UpdateUserRow struct {
	ID              int64          `json:"id"`
	ActivationToken sql.NullString `json:"activation_token"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser, arg.ID, arg.ActivationToken, arg.IsActive)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.ActivationToken, &i.IsActive)
	return i, err
}
